# Generated by Django 5.0.7 on 2024-07-27 11:38

import django.db.models.deletion
import django.forms.widgets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassId', models.IntegerField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=50)),
                ('Semester', models.CharField(max_length=50)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StuId', models.IntegerField(db_column='Student ID', primary_key=True, serialize=False)),
                ('StuName', models.CharField(db_column='Student name', max_length=50)),
                ('StuImg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeachId', models.IntegerField(db_column='Teacher ID', primary_key=True, serialize=False)),
                ('TeachName', models.CharField(max_length=50, verbose_name='Teacher name')),
                ('Email', models.EmailField(max_length=254)),
                ('Pass', models.CharField(max_length=50, verbose_name=django.forms.widgets.PasswordInput)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('SlotId', models.IntegerField(primary_key=True, serialize=False)),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.student')),
            ],
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('SlotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.slot')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.student')),
                ('TimeFrameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.timeframe')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attend', models.BinaryField()),
                ('ClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.class')),
                ('SlotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.slot')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.student')),
                ('TimeFrameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicConcepts.timeframe')),
            ],
        ),
    ]
