# Generated by Django 5.0.7 on 2024-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Subject',
        ),
        migrations.AddField(
            model_name='slot',
            name='SlotSubject',
            field=models.CharField(default='Math', max_length=50),
            preserve_default=False,
        ),
    ]
