# Generated by Django 5.0.7 on 2024-08-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slot_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
