# Generated by Django 5.1 on 2024-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
