# Generated by Django 5.0.7 on 2024-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0002_remove_class_subject_slot_slotsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='StudentId',
        ),
        migrations.AddField(
            model_name='slot',
            name='SlotTime',
            field=models.DateField(auto_now=True),
        ),
    ]
