# Generated by Django 5.0.7 on 2024-07-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicConcepts', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
